-- Complete all product descriptions with comprehensive bilingual content

-- 1000 Series products
UPDATE products SET descriptionEn = 'An epoxy-based repair composite with extended working life for metal repair applications. Super XL-Metal provides longer working time for complex repairs while maintaining excellent mechanical properties. The two-part system offers superior adhesion and can be applied to wet and oil-contaminated surfaces. Suitable for emergency repairs where extended working time is critical.', descriptionEl = 'Ένα σύνθετο υλικό επιδιόρθωσης βάσης εποξειδίνης με παρατεταμένο χρόνο εργασίας για εφαρμογές επιδιόρθωσης μετάλλων. Το Super XL-Metal παρέχει μεγαλύτερο χρόνο εργασίας για πολύπλοκες επιδιορθώσεις διατηρώντας εξαιρετικές μηχανικές ιδιότητες. Το σύστημα δύο συστατικών προσφέρει ανώτερη συγκόλληση και μπορεί να εφαρμοστεί σε υγρές και λαδωμένες επιφάνειες.' WHERE code = '1121';

UPDATE products SET descriptionEn = 'A metal repair composite specifically formulated for rebuilding pitting and metal loss caused by erosion and corrosion. Smoothing Metal provides a smooth, protective surface that improves fluid flow and reduces turbulence in pipes and equipment. The material offers excellent adhesion and can be applied to vertical and overhead surfaces. Ideal for restoring damaged equipment to original specifications.', descriptionEl = 'Ένα σύνθετο υλικό επιδιόρθωσης μετάλλου ειδικά διατυπωμένο για αναδόμηση κοιλοτήτων και απώλειας μετάλλου που προκαλούνται από διάβρωση και διάβρωση. Το Smoothing Metal παρέχει μια λεία, προστατευτική επιφάνεια που βελτιώνει τη ροή του ρευστού και μειώνει τις στροβιλισμούς σε σωλήνες και εξοπλισμό. Το υλικό προσφέρει εξαιρετική συγκόλληση και μπορεί να εφαρμοστεί σε κάθετες και οριζόντιες επιφάνειες.' WHERE code = '1151';

UPDATE products SET descriptionEn = 'An epoxy-based repair composite specifically engineered for application to wet and oil-contaminated metal surfaces. Super UW-Metal (Ultra Wet) provides surface tolerance that allows repairs to be made even when conventional materials would fail. The two-part system maintains excellent mechanical properties and adhesion despite surface contamination. Essential for emergency repairs in harsh industrial environments.', descriptionEl = 'Ένα σύνθετο υλικό επιδιόρθωσης βάσης εποξειδίνης ειδικά σχεδιασμένο για εφαρμογή σε υγρές και λαδωμένες επιφάνειες μετάλλου. Το Super UW-Metal (Ultra Wet) παρέχει ανοχή επιφάνειας που επιτρέπει τις επιδιορθώσεις ακόμη και όταν τα συμβατικά υλικά θα απέτυχαν. Το σύστημα δύο συστατικών διατηρεί εξαιρετικές μηχανικές ιδιότητες και συγκόλληση παρά τη ρύπανση της επιφάνειας.' WHERE code = '1161';

UPDATE products SET descriptionEn = 'A surface-tolerant epoxy composite specifically formulated for emergency in-situ metal repair of oil-contaminated, wet, and underwater substrates. This advanced material allows repairs to be made in challenging conditions where traditional composites cannot be applied. Ideal for offshore platforms, marine vessels, and industrial equipment requiring immediate repair without extensive surface preparation.', descriptionEl = 'Ένα σύνθετο υλικό εποξειδίνης ανοχής επιφάνειας ειδικά διατυπωμένο για έκτακτη επιδιόρθωση μετάλλου in-situ λαδωμένων, υγρών και υποβρύχιων υποστρωμάτων. Αυτό το προηγμένο υλικό επιτρέπει τις επιδιορθώσεις σε δύσκολες συνθήκες όπου τα παραδοσιακά σύνθετα δεν μπορούν να εφαρμοστούν. Ιδανικό για θαλάσσιες πλατφόρμες, θαλάσσια σκάφη και βιομηχανικό εξοπλισμό που απαιτεί άμεση επιδιόρθωση.' WHERE code = '1212';

UPDATE products SET descriptionEn = 'A fast-curing metal repair composite engineered for high-speed emergency repairs where rapid turnaround is critical. Super E-Metal provides accelerated cure times while maintaining excellent mechanical properties and adhesion. The two-part system allows repairs to be completed and put back into service quickly, minimizing downtime. Ideal for production environments where equipment availability is essential.', descriptionEl = 'Ένα γρήγορα σκληρυνόμενο σύνθετο υλικό επιδιόρθωσης μετάλλου σχεδιασμένο για έκτακτες επιδιορθώσεις υψηλής ταχύτητας όπου η γρήγορη αποπεράτωση είναι κρίσιμη. Το Super E-Metal παρέχει επιταχυνόμενους χρόνους σκλήρυνσης διατηρώντας εξαιρετικές μηχανικές ιδιότητες και συγκόλληση. Το σύστημα δύο συστατικών επιτρέπει τις επιδιορθώσεις να ολοκληρωθούν και να επιστρέψουν σε λειτουργία γρήγορα, ελαχιστοποιώντας το χρόνο διακοπής.' WHERE code = '1221';

UPDATE products SET descriptionEn = 'A heat-activated metal repair composite designed for in-situ repair and protection of hot metal surfaces with minimal surface preparation. HA-Metal activates when exposed to elevated temperatures, allowing repairs to be made on equipment operating at 80-200°C. The material provides excellent adhesion and mechanical properties without requiring extensive grinding or cleaning. Ideal for emergency repairs on operating equipment.', descriptionEl = 'Ένα σύνθετο υλικό επιδιόρθωσης μετάλλου ενεργοποιούμενο από θερμότητα σχεδιασμένο για επιδιόρθωση και προστασία θερμών επιφανειών μετάλλου με ελάχιστη προετοιμασία επιφάνειας. Το HA-Metal ενεργοποιείται όταν εκτίθεται σε υψηλές θερμοκρασίες, επιτρέποντας τις επιδιορθώσεις σε εξοπλισμό που λειτουργεί στους 80-200°C. Το υλικό παρέχει εξαιρετική συγκόλληση και μηχανικές ιδιότητες χωρίς να απαιτείται εκτεταμένη λείανση ή καθαρισμός.' WHERE code = '1251';

UPDATE products SET descriptionEn = 'A ceramic-filled epoxy coating engineered to provide erosion and corrosion resistance of metal surfaces. The coating creates a protective barrier that prevents direct contact between corrosive media and the substrate. Ceramic S-Metal offers excellent adhesion and can be applied by spray or brush. Ideal for protecting equipment in chemical plants, refineries, and marine environments.', descriptionEl = 'Ένα εποξειδικό επίχρισμα γεμάτο κεραμικά σχεδιασμένο για να παρέχει αντίσταση στη διάβρωση και τη διάβρωση των επιφανειών μετάλλου. Το επίχρισμα δημιουργεί μια προστατευτική φραγή που αποτρέπει την άμεση επαφή μεταξύ διαβρωτικών μέσων και του υποστρώματος. Το Ceramic S-Metal προσφέρει εξαιρετική συγκόλληση και μπορεί να εφαρμοστεί με ψεκασμό ή βούρτσα. Ιδανικό για προστασία εξοπλισμού σε χημικές εγκαταστάσεις, διυλιστήρια και θαλάσσια περιβάλλοντα.' WHERE code = '1321';

UPDATE products SET descriptionEn = 'A spray or brush-applied epoxy coating providing erosion and corrosion protection of equipment operating under continuous immersion. This high-performance coating creates a durable barrier against chemical attack and erosive conditions. Ideal for internal lining of pipes, tanks, and heat exchangers. Offers excellent adhesion and can be applied to various substrates including steel and concrete.', descriptionEl = 'Ένα εποξειδικό επίχρισμα που εφαρμόζεται με ψεκασμό ή βούρτσα παρέχοντας προστασία από διάβρωση και διάβρωση του εξοπλισμού που λειτουργεί υπό συνεχή βύθιση. Αυτό το υψηλής απόδοσης επίχρισμα δημιουργεί μια ανθεκτική φραγή κατά της χημικής επίθεσης και των διαβρωτικών συνθηκών. Ιδανικό για εσωτερική επένδυση σωλήνων, δεξαμενών και εναλλακτών θερμότητας. Προσφέρει εξαιρετική συγκόλληση και μπορεί να εφαρμοστεί σε διάφορα υποστρώματα συμπεριλαμβανομένου χάλυβα και σκυροδέματος.' WHERE code = '1331';

UPDATE products SET descriptionEn = 'An NSF/ANSI 61 approved epoxy coating engineered to improve efficiency of pumps, pipes, valves and other fluid handling equipment while providing outstanding erosion and corrosion protection. This food-grade coating is safe for contact with potable water and drinking water systems. Supermetalglide N combines superior performance with regulatory compliance for water treatment applications.', descriptionEl = 'Ένα εποξειδικό επίχρισμα εγκεκριμένο από NSF/ANSI 61 σχεδιασμένο για βελτίωση της απόδοσης αντλιών, σωλήνων, βαλβίδων και άλλου εξοπλισμού χειρισμού ρευστών. Αυτό το επίχρισμα ασφαλές για τρόφιμα είναι ασφαλές για επαφή με πόσιμο νερό και συστήματα πόσιμου νερού. Το Supermetalglide N συνδυάζει ανώτερη απόδοση με συμμόρφωση κανονισμών για εφαρμογές επεξεργασίας νερού.' WHERE code = '1341N';

UPDATE products SET descriptionEn = 'A spray-applied epoxy coating for corrosion protection of high temperature equipment operating under immersion. This advanced formulation provides long-term protection against chemical attack and erosive conditions while maintaining performance at elevated temperatures. Ideal for heat exchangers, boiler tubes, and other high-temperature equipment in power generation and petrochemical industries.', descriptionEl = 'Ένα εποξειδικό επίχρισμα που εφαρμόζεται με ψεκασμό για προστασία από διάβρωση του εξοπλισμού υψηλής θερμοκρασίας που λειτουργεί υπό βύθιση. Αυτή η προηγμένη διατύπωση παρέχει μακροχρόνια προστασία κατά της χημικής επίθεσης και των διαβρωτικών συνθηκών διατηρώντας την απόδοση σε υψηλές θερμοκρασίες. Ιδανικό για εναλλάκτες θερμότητας, σωλήνες λέβητα και άλλο εξοπλισμό υψηλής θερμοκρασίας.' WHERE code = '1391S';

UPDATE products SET descriptionEn = 'Hand-applied erosion and corrosion resistant coating for high temperature equipment operating under immersion. This high-performance epoxy provides excellent protection against chemical attack and erosive conditions. Ideal for complex geometries and areas where spray application is not practical. Maintains protective properties even at elevated temperatures.', descriptionEl = 'Χειροποίητο επίχρισμα αντίστασης στη διάβρωση και τη διάβρωση για εξοπλισμό υψηλής θερμοκρασίας που λειτουργεί υπό βύθιση. Αυτό το υψηλής απόδοσης εποξειδικό παρέχει εξαιρετική προστασία κατά της χημικής επίθεσης και των διαβρωτικών συνθηκών. Ιδανικό για πολύπλοκες γεωμετρίες και περιοχές όπου ο ψεκασμός δεν είναι πρακτικός. Διατηρεί τις προστατευτικές ιδιότητες ακόμη και σε υψηλές θερμοκρασίες.' WHERE code = '1391T';

UPDATE products SET descriptionEn = 'Erosion, corrosion and chemical resistant coating for high temperature equipment operating under immersion. Ceramic HT2 combines ceramic reinforcement with high-temperature epoxy technology to provide superior protection in demanding industrial environments. Ideal for equipment exposed to aggressive chemical media and high temperatures simultaneously.', descriptionEl = 'Επίχρισμα αντίστασης στη διάβρωση, διάβρωση και χημικές ουσίες για εξοπλισμό υψηλής θερμοκρασίας που λειτουργεί υπό βύθιση. Το Ceramic HT2 συνδυάζει κεραμική ενίσχυση με τεχνολογία εποξειδίνης υψηλής θερμοκρασίας για να παρέχει ανώτερη προστασία σε απαιτητικά βιομηχανικά περιβάλλοντα. Ιδανικό για εξοπλισμό που εκτίθεται σε επιθετικά χημικά μέσα και υψηλές θερμοκρασίες ταυτόχρονα.' WHERE code = '1392';

UPDATE products SET descriptionEn = 'High temperature epoxy repair composite for rebuilding equipment damaged by erosion and corrosion. Super HT-Metal provides excellent mechanical properties and adhesion even at elevated temperatures. Ideal for repair of high-temperature equipment in power generation, petrochemical, and steel manufacturing industries. Can be applied to equipment operating at temperatures up to 200°C.', descriptionEl = 'Σύνθετο υλικό επιδιόρθωσης εποξειδίνης υψηλής θερμοκρασίας για αναδόμηση εξοπλισμού που έχει ζημιωθεί από διάβρωση και διάβρωση. Το Super HT-Metal παρέχει εξαιρετικές μηχανικές ιδιότητες και συγκόλληση ακόμη και σε υψηλές θερμοκρασίες. Ιδανικό για επιδιόρθωση εξοπλισμού υψηλής θερμοκρασίας στη δημιουργία ηλεκτρικής ενέργειας, τις πετροχημικές και τις βιομηχανίες κατασκευής χάλυβα.' WHERE code = '1511';

UPDATE products SET descriptionEn = 'High temperature spray-applied epoxy coating for internal lining of equipment operating under continuous immersion conditions, which provides outstanding corrosion resistance. This advanced formulation maintains protective properties even at elevated temperatures and in aggressive chemical environments. Ideal for power generation and petrochemical applications.', descriptionEl = 'Εποξειδικό επίχρισμα που εφαρμόζεται με ψεκασμό υψηλής θερμοκρασίας για εσωτερική επένδυση εξοπλισμού που λειτουργεί υπό συνεχή βύθιση, παρέχοντας εξαιρετική αντίσταση στη διάβρωση. Αυτή η προηγμένη διατύπωση διατηρεί τις προστατευτικές ιδιότητες ακόμη και σε υψηλές θερμοκρασίες και σε επιθετικά χημικά περιβάλλοντα. Ιδανικό για εφαρμογές δημιουργίας ηλεκτρικής ενέργειας και πετροχημικών.' WHERE code = '1523';

UPDATE products SET descriptionEn = 'High temperature hand-applied epoxy coating for internal lining of equipment operating under continuous immersion conditions, which provides outstanding corrosion resistance. Ideal for complex geometries and areas where spray application is not practical. Maintains protective properties even at elevated temperatures in aggressive chemical environments.', descriptionEl = 'Χειροποίητο εποξειδικό επίχρισμα υψηλής θερμοκρασίας για εσωτερική επένδυση εξοπλισμού που λειτουργεί υπό συνεχή βύθιση, παρέχοντας εξαιρετική αντίσταση στη διάβρωση. Ιδανικό για πολύπλοκες γεωμετρίες και περιοχές όπου ο ψεκασμός δεν είναι πρακτικός. Διατηρεί τις προστατευτικές ιδιότητες ακόμη και σε υψηλές θερμοκρασίες σε επιθετικά χημικά περιβάλλοντα.' WHERE code = '1593';

UPDATE products SET descriptionEn = 'An abrasion resistant composite material for the repair and lining of metal surfaces subject to erosive attack. Ceramic Carbide provides superior protection against fine particle erosion and abrasive wear. Ideal for equipment handling abrasive materials such as sand, minerals, and other particulates. Can be applied to vertical and overhead surfaces.', descriptionEl = 'Ένα σύνθετο υλικό αντίστασης στη φθορά για επιδιόρθωση και επένδυση μεταλλικών επιφανειών που υπόκεινται σε διαβρωτική επίθεση. Το Ceramic Carbide παρέχει ανώτερη προστασία κατά της διάβρωσης λεπτών σωματιδίων και της φθοράς από τριβή. Ιδανικό για εξοπλισμό που χειρίζεται φθοράς υλικά όπως άμμος, ορυκτά και άλλα σωματίδια. Μπορεί να εφαρμοστεί σε κάθετες και οριζόντιες επιφάνειες.' WHERE code = '1811';

UPDATE products SET descriptionEn = 'An abrasion resistant composite material for the repair and lining of metal surfaces suffering from fine particle erosion. Ceramic Carbide FP is specifically formulated to handle fine particle erosion applications such as coal handling, fly ash, and other fine particulate systems. Provides excellent protection and extended service life.', descriptionEl = 'Ένα σύνθετο υλικό αντίστασης στη φθορά για επιδιόρθωση και επένδυση μεταλλικών επιφανειών που υπόφερουν από διάβρωση λεπτών σωματιδίων. Το Ceramic Carbide FP είναι ειδικά διατυπωμένο για εφαρμογές διάβρωσης λεπτών σωματιδίων όπως χειρισμός άνθρακα, πτητική τέφρα και άλλα συστήματα λεπτών σωματιδίων. Παρέχει εξαιρετική προστασία και επεκταμένη διάρκεια ζωής.' WHERE code = '1812';

UPDATE products SET descriptionEn = 'A highly abrasion resistant composite material for the repair and lining of metal surfaces operating at high temperatures. This advanced formulation maintains protective properties even at elevated temperatures while providing superior abrasion resistance. Ideal for high-temperature erosion applications in power generation and industrial processing.', descriptionEl = 'Ένα εξαιρετικά αντίστασης στη φθορά σύνθετο υλικό για επιδιόρθωση και επένδυση μεταλλικών επιφανειών που λειτουργούν σε υψηλές θερμοκρασίες. Αυτή η προηγμένη διατύπωση διατηρεί τις προστατευτικές ιδιότητες ακόμη και σε υψηλές θερμοκρασίες παρέχοντας ανώτερη αντίσταση στη φθορά. Ιδανικό για εφαρμογές διάβρωσης υψηλής θερμοκρασίας στη δημιουργία ηλεκτρικής ενέργειας και τη βιομηχανική επεξεργασία.' WHERE code = '1813';

UPDATE products SET descriptionEn = 'An abrasion resistant composite material for the repair and protection of metal surfaces. This general-purpose abrasion resistant system provides excellent protection against erosive wear and impact damage. Suitable for a wide range of industrial applications where abrasion resistance is required. Can be applied to vertical and overhead surfaces.', descriptionEl = 'Ένα σύνθετο υλικό αντίστασης στη φθορά για επιδιόρθωση και προστασία μεταλλικών επιφανειών. Αυτό το σύστημα αντίστασης στη φθορά γενικής χρήσης παρέχει εξαιρετική προστασία κατά της διαβρωτικής φθοράς και της ζημιάς από κρούση. Κατάλληλο για ένα ευρύ φάσμα βιομηχανικών εφαρμογών όπου απαιτείται αντίσταση στη φθορά. Μπορεί να εφαρμοστεί σε κάθετες και οριζόντιες επιφάνειες.' WHERE code = '1814';

UPDATE products SET descriptionEn = 'A fast curing, surface tolerant, abrasion resistant general-purpose protection system. This advanced composite provides rapid cure times while maintaining excellent abrasion resistance and adhesion even on contaminated surfaces. Ideal for emergency repairs and applications where quick turnaround is essential. Suitable for a wide range of industrial applications.', descriptionEl = 'Ένα σύστημα προστασίας γενικής χρήσης γρήγορης σκλήρυνσης, ανοχής επιφάνειας και αντίστασης στη φθορά. Αυτό το προηγμένο σύνθετο παρέχει γρήγορους χρόνους σκλήρυνσης διατηρώντας εξαιρετική αντίσταση στη φθορά και συγκόλληση ακόμη και σε ρυπασμένες επιφάνειες. Ιδανικό για έκτακτες επιδιορθώσεις και εφαρμογές όπου η γρήγορη αποπεράτωση είναι απαραίτητη.' WHERE code = '1818';

UPDATE products SET descriptionEn = 'Epoxy coating system used in conjunction with Belzona aggregates to reduce slippage on metallic surfaces. Fluid Metal provides a durable, slip-resistant surface for safety applications on stairs, ramps, walkways, and other areas where slip resistance is critical. Can be applied to vertical and overhead surfaces. Ideal for industrial facilities and public areas.', descriptionEl = 'Σύστημα εποξειδικού επιχρίσματος που χρησιμοποιείται σε συνδυασμό με συγκεντρώματα Belzona για μείωση της ολίσθησης σε μεταλλικές επιφάνειες. Το Fluid Metal παρέχει μια ανθεκτική, αντιολισθητική επιφάνεια για εφαρμογές ασφαλείας σε σκάλες, ράμπες, διαδρόμους και άλλες περιοχές όπου η αντιολίσθηση είναι κρίσιμη. Μπορεί να εφαρμοστεί σε κάθετες και οριζόντιες επιφάνειες. Ιδανικό για βιομηχανικές εγκαταστάσεις και δημόσιες περιοχές.' WHERE code = '1821';

-- 2000 Series products
UPDATE products SET descriptionEn = 'A flexible abrasion resistant polyurethane elastomer for the casting of rubber components and coating of metal and rubber surfaces. D&A Fluid Elastomer provides excellent flexibility and abrasion resistance. Ideal for creating new rubber components or coating existing surfaces that require flexibility and durability. Can be applied to vertical and overhead surfaces.', descriptionEl = 'Ένα ευέλικτο πολυουρεθανικό ελαστομερές αντίστασης στη φθορά για την κατασκευή εξαρτημάτων από καουτσούκ και επίχρισμα μεταλλικών και ελαστικών επιφανειών. Το D&A Fluid Elastomer παρέχει εξαιρετική ευελιξία και αντίσταση στη φθορά. Ιδανικό για δημιουργία νέων εξαρτημάτων από καουτσούκ ή επίχρισμα υπαρχόντων επιφανειών που απαιτούν ευελιξία και ανθεκτικότητα.' WHERE code = '2131';

UPDATE products SET descriptionEn = 'A flexible cavitation and abrasion resistant polyurethane elastomer for the coating of metal and rubber components. ACR-Fluid Elastomer provides superior protection against cavitation damage and abrasive wear. Ideal for pump impellers, propellers, and other equipment operating in cavitation-prone environments. Maintains flexibility and protective properties even under extreme conditions.', descriptionEl = 'Ένα ευέλικτο πολυουρεθανικό ελαστομερές αντίστασης στη σπηλαίωση και τη φθορά για επίχρισμα μεταλλικών και ελαστικών εξαρτημάτων. Το ACR-Fluid Elastomer παρέχει ανώτερη προστασία κατά της ζημιάς από σπηλαίωση και της φθοράς από τριβή. Ιδανικό για πτερύγια αντλιών, έλικες και άλλο εξοπλισμό που λειτουργεί σε περιβάλλοντα επιρρεπή σε σπηλαίωση. Διατηρεί ευελιξία και προστατευτικές ιδιότητες ακόμη και υπό ακραίες συνθήκες.' WHERE code = '2141';

UPDATE products SET descriptionEn = 'A flexible multi-purpose polyurethane elastomer for the repair, rebuilding and coating of rubber components and metal surfaces. MP Hi-Build Elastomer provides excellent flexibility and durability. Ideal for general-purpose elastomer applications where flexibility and abrasion resistance are required. Can be applied to vertical and overhead surfaces.', descriptionEl = 'Ένα ευέλικτο πολυουρεθανικό ελαστομερές πολλαπλών χρήσεων για επιδιόρθωση, αναδόμηση και επίχρισμα εξαρτημάτων από καουτσούκ και μεταλλικών επιφανειών. Το MP Hi-Build Elastomer παρέχει εξαιρετική ευελιξία και ανθεκτικότητα. Ιδανικό για εφαρμογές ελαστομερών γενικής χρήσης όπου απαιτούνται ευελιξία και αντίσταση στη φθορά. Μπορεί να εφαρμοστεί σε κάθετες και οριζόντιες επιφάνειες.' WHERE code = '2211';

UPDATE products SET descriptionEn = 'A tough, flexible multi-purpose polyurethane elastomer for the repair and coating of rubber components and metal surfaces and casting of new components. MP Fluid Elastomer combines toughness with flexibility for demanding applications. Ideal for creating new rubber components or repairing existing equipment that requires both flexibility and durability. Maintains properties even under extreme conditions.', descriptionEl = 'Ένα σκληρό, ευέλικτο πολυουρεθανικό ελαστομερές πολλαπλών χρήσεων για επιδιόρθωση και επίχρισμα εξαρτημάτων από καουτσούκ και μεταλλικών επιφανειών και κατασκευή νέων εξαρτημάτων. Το MP Fluid Elastomer συνδυάζει σκληρότητα με ευελιξία για απαιτητικές εφαρμογές. Ιδανικό για δημιουργία νέων εξαρτημάτων από καουτσούκ ή επιδιόρθωση υπάρχοντος εξοπλισμού που απαιτεί τόσο ευελιξία όσο και ανθεκτικότητα.' WHERE code = '2221';

UPDATE products SET descriptionEn = 'A fast-curing, abrasion resistant polyurethane elastomer for high speed emergency repairs, rebuilding and coating of rubber components and metal surfaces. SR Elastomer provides rapid cure times while maintaining excellent abrasion resistance and flexibility. Ideal for emergency repairs where quick turnaround is essential. Maintains protective properties even under extreme conditions.', descriptionEl = 'Ένα γρήγορα σκληρυνόμενο, αντίστασης στη φθορά πολυουρεθανικό ελαστομερές για έκτακτες επιδιορθώσεις υψηλής ταχύτητας, αναδόμηση και επίχρισμα εξαρτημάτων από καουτσούκ και μεταλλικών επιφανειών. Το SR Elastomer παρέχει γρήγορους χρόνους σκλήρυνσης διατηρώντας εξαιρετική αντίσταση στη φθορά και ευελιξία. Ιδανικό για έκτακτες επιδιορθώσεις όπου η γρήγορη αποπεράτωση είναι απαραίτητη. Διατηρεί τις προστατευτικές ιδιότητες ακόμη και υπό ακραίες συνθήκες.' WHERE code = '2311';

-- 3000 Series products
UPDATE products SET descriptionEn = 'A liquid-applied roof coating for long-term protection and waterproofing of roofs which can be applied during winter weather conditions. WG Membrane provides flexible, seamless protection that accommodates building movement and thermal expansion. The coating offers UV protection and excellent durability. Ideal for flat roofs, pitched roofs, and complex roof geometries in cold climates.', descriptionEl = 'Ένα εποξειδικό επίχρισμα στέγης που εφαρμόζεται σε υγρή μορφή για μακροχρόνια προστασία και αδιαβροχοποίηση στεγών που μπορεί να εφαρμοστεί κατά τις χειμερινές καιρικές συνθήκες. Το WG Membrane παρέχει ευέλικτη, ενιαία προστασία που προσαρμόζεται στη κίνηση του κτιρίου και τη θερμική διαστολή. Το επίχρισμα προσφέρει προστασία από τις υπεριώδεις ακτίνες και εξαιρετική ανθεκτικότητα. Ιδανικό για επίπεδες στέγες, κεκλιμένες στέγες και πολύπλοκες γεωμετρίες στεγών σε ψυχρά κλίματα.' WHERE code = '3131';

UPDATE products SET descriptionEn = 'A single component, seamless and flexible coating for encapsulation of all types of thermal insulation and cladding systems. Lagseal provides durable protection against moisture ingress and environmental degradation. Ideal for protecting insulation systems on pipes, tanks, and building structures. Maintains flexibility and protective properties over extended service life.', descriptionEl = 'Ένα ενιαίο συστατικό, ενιαίο και ευέλικτο επίχρισμα για ενθυλάκωση όλων των τύπων θερμικής μόνωσης και συστημάτων επένδυσης. Το Lagseal παρέχει ανθεκτική προστασία κατά της διείσδυσης υγρασίας και της περιβαλλοντικής υποβάθμισης. Ιδανικό για προστασία συστημάτων μόνωσης σε σωλήνες, δεξαμενές και κτιριακές δομές. Διατηρεί ευελιξία και προστατευτικές ιδιότητες κατά τη διάρκεια της επεκταμένης διάρκειας ζωής.' WHERE code = '3211';

UPDATE products SET descriptionEn = 'Flexible and peelable system, used for encapsulating flanges and bolt fastenings to protect against moisture ingress and prevent corrosion. This innovative system provides temporary or semi-permanent protection that can be easily removed if needed. Ideal for protecting critical connection points in industrial equipment. Maintains protective properties even in harsh environments.', descriptionEl = 'Ευέλικτο και αποφλοιώσιμο σύστημα, που χρησιμοποιείται για ενθυλάκωση φλάντζων και κοχλιοσυνδέσμων για προστασία κατά της διείσδυσης υγρασίας και πρόληψη της διάβρωσης. Αυτό το καινοτόμο σύστημα παρέχει προσωρινή ή ημι-μόνιμη προστασία που μπορεί να αφαιρεθεί εύκολα εάν χρειάζεται. Ιδανικό για προστασία κρίσιμων σημείων σύνδεσης σε βιομηχανικό εξοπλισμό. Διατηρεί τις προστατευτικές ιδιότητες ακόμη και σε σκληρά περιβάλλοντα.' WHERE code = '3412';

-- 4000 Series products  
UPDATE products SET descriptionEn = 'An epoxy-based resin designed to be used with an aggregate for the reparation, resurfacing and rebuilding of concrete and stonework damaged by impact, vibration, chemical and environmental attack. Bulkfill provides excellent strength and durability. Ideal for large-scale concrete repairs where volume and strength are required. Can be applied to vertical and overhead surfaces.', descriptionEl = 'Μια εποξειδική ρητίνη σχεδιασμένη για χρήση με συγκέντρωμα για την επιδιόρθωση, αναδόμηση και αναδόμηση σκυροδέματος και πετρόχτιστων που έχουν ζημιωθεί από κρούση, δόνηση, χημική και περιβαλλοντική επίθεση. Το Bulkfill παρέχει εξαιρετική αντοχή και ανθεκτικότητα. Ιδανικό για μεγάλης κλίμακας επιδιορθώσεις σκυροδέματος όπου απαιτούνται όγκος και αντοχή. Μπορεί να εφαρμοστεί σε κάθετες και οριζόντιες επιφάνειες.' WHERE code = '4124';

UPDATE products SET descriptionEn = 'An epoxy repair composite for the resurfacing and protection of concrete and stone areas. Magma-Screed provides excellent surface finish and protection against chemical attack and environmental degradation. Ideal for resurfacing damaged concrete floors and walls. Offers excellent adhesion and can be applied to various substrates including concrete and stone.', descriptionEl = 'Ένα σύνθετο υλικό επιδιόρθωσης εποξειδίνης για αναδόμηση και προστασία περιοχών σκυροδέματος και πετρόχτιστων. Το Magma-Screed παρέχει εξαιρετικό φινίρισμα επιφάνειας και προστασία κατά της χημικής επίθεσης και της περιβαλλοντικής υποβάθμισης. Ιδανικό για αναδόμηση ζημιασμένων δαπέδων και τοίχων από σκυρόδεμα. Προσφέρει εξαιρετική συγκόλληση και μπορεί να εφαρμοστεί σε διάφορα υποστρώματα συμπεριλαμβανομένου σκυροδέματος και πετρόχτιστων.' WHERE code = '4131';

UPDATE products SET descriptionEn = 'An epoxy resin for the treatment and protection of concrete surfaces exposed to chemical attack and abrasion. Magma-Quartz Resin provides excellent protection and can be used with aggregates for enhanced performance. Ideal for creating protective coatings on concrete floors and structures in industrial environments. Offers superior chemical resistance and durability.', descriptionEl = 'Μια εποξειδική ρητίνη για τη θεραπεία και προστασία των επιφανειών σκυροδέματος που εκτίθενται σε χημική επίθεση και φθορά. Η Magma-Quartz Resin παρέχει εξαιρετική προστασία και μπορεί να χρησιμοποιηθεί με συγκεντρώματα για βελτιωμένη απόδοση. Ιδανικό για δημιουργία προστατευτικών επιχρισμάτων σε δάπεδα σκυροδέματος και δομές σε βιομηχανικά περιβάλλοντα. Προσφέρει ανώτερη χημική αντίσταση και ανθεκτικότητα.' WHERE code = '4151';

UPDATE products SET descriptionEn = 'An epoxy-based resin designed to be used with an aggregate for the reparation, resurfacing and rebuilding of concrete and stonework damaged by impact, vibration, chemical and environmental attack. Bulkfill Resin provides excellent strength and durability. Ideal for large-scale concrete repairs where volume and strength are required. Maintains protective properties even in harsh chemical environments.', descriptionEl = 'Μια εποξειδική ρητίνη σχεδιασμένη για χρήση με συγκέντρωμα για την επιδιόρθωση, αναδόμηση και αναδόμηση σκυροδέματος και πετρόχτιστων που έχουν ζημιωθεί από κρούση, δόνηση, χημική και περιβαλλοντική επίθεση. Η Bulkfill Resin παρέχει εξαιρετική αντοχή και ανθεκτικότητα. Ιδανικό για μεγάλης κλίμακας επιδιορθώσεις σκυροδέματος όπου απαιτούνται όγκος και αντοχή. Διατηρεί τις προστατευτικές ιδιότητες ακόμη και σε σκληρά χημικά περιβάλλοντα.' WHERE code = '4154';

UPDATE products SET descriptionEn = 'An acid and heat resistant epoxy repair composite for concrete and stone repair, resurfacing and protection. AHR Magma-Quartz provides superior protection against acid attack and elevated temperatures. Ideal for equipment and structures in chemical plants, refineries, and other facilities handling aggressive chemicals. Maintains protective properties even at elevated temperatures.', descriptionEl = 'Ένα σύνθετο υλικό επιδιόρθωσης εποξειδίνης ανθεκτικό στο οξύ και τη θερμότητα για επιδιόρθωση, αναδόμηση και προστασία σκυροδέματος και πετρόχτιστων. Το AHR Magma-Quartz παρέχει ανώτερη προστασία κατά της επίθεσης οξέος και των υψηλών θερμοκρασιών. Ιδανικό για εξοπλισμό και δομές σε χημικές εγκαταστάσεις, διυλιστήρια και άλλες εγκαταστάσεις που χειρίζονται επιθετικές χημικές ουσίες. Διατηρεί τις προστατευτικές ιδιότητες ακόμη και σε υψηλές θερμοκρασίες.' WHERE code = '4181';

UPDATE products SET descriptionEn = 'A chemical resistant epoxy material for rebuilding metal and concrete surfaces and protection against chemical attack. Magma CR1 Hi-Build provides thick-build capability for substantial repairs. Ideal for equipment and structures exposed to aggressive chemicals. Offers excellent adhesion and can be applied to vertical and overhead surfaces.', descriptionEl = 'Ένα χημικά ανθεκτικό εποξειδικό υλικό για αναδόμηση μεταλλικών και σκυροδέματος επιφανειών και προστασία κατά της χημικής επίθεσης. Το Magma CR1 Hi-Build παρέχει δυνατότητα παχιάς δόμησης για σημαντικές επιδιορθώσεις. Ιδανικό για εξοπλισμό και δομές που εκτίθενται σε επιθετικές χημικές ουσίες. Προσφέρει εξαιρετική συγκόλληση και μπορεί να εφαρμοστεί σε κάθετες και οριζόντιες επιφάνειες.' WHERE code = '4301';

UPDATE products SET descriptionEn = 'A chemical resistant epoxy coating for protection of concrete and metal surfaces. Magma CR1 provides excellent protection against chemical attack and environmental degradation. Ideal for equipment and structures in chemical plants, refineries, and other industrial facilities. Offers superior durability and long-term protection.', descriptionEl = 'Ένα χημικά ανθεκτικό εποξειδικό επίχρισμα για προστασία των επιφανειών σκυροδέματος και μετάλλου. Το Magma CR1 παρέχει εξαιρετική προστασία κατά της χημικής επίθεσης και της περιβαλλοντικής υποβάθμισης. Ιδανικό για εξοπλισμό και δομές σε χημικές εγκαταστάσεις, διυλιστήρια και άλλες βιομηχανικές εγκαταστάσεις. Προσφέρει ανώτερη ανθεκτικότητα και μακροχρόνια προστασία.' WHERE code = '4311';

UPDATE products SET descriptionEn = 'A high temperature epoxy coating for the protection of concrete and metal surfaces in contact with hot organic acids and other chemicals. Magma CR3 provides excellent protection even at elevated temperatures. Ideal for equipment in chemical plants and refineries handling hot aggressive chemicals. Maintains protective properties even under extreme conditions.', descriptionEl = 'Ένα εποξειδικό επίχρισμα υψηλής θερμοκρασίας για προστασία των επιφανειών σκυροδέματος και μετάλλου σε επαφή με θερμά οργανικά οξέα και άλλες χημικές ουσίες. Το Magma CR3 παρέχει εξαιρετική προστασία ακόμη και σε υψηλές θερμοκρασίες. Ιδανικό για εξοπλισμό σε χημικές εγκαταστάσεις και διυλιστήρια που χειρίζονται θερμές επιθετικές χημικές ουσίες. Διατηρεί τις προστατευτικές ιδιότητες ακόμη και υπό ακραίες συνθήκες.' WHERE code = '4331';

UPDATE products SET descriptionEn = 'A high temperature epoxy coating for concrete and metal surfaces in contact with hot inorganic acids. Magma CR4 provides superior protection against acid attack at elevated temperatures. Ideal for equipment in refineries and chemical plants handling hot inorganic acids. Maintains protective properties even at extreme temperatures and in highly aggressive chemical environments.', descriptionEl = 'Ένα εποξειδικό επίχρισμα υψηλής θερμοκρασίας για επιφάνειες σκυροδέματος και μετάλλου σε επαφή με θερμά ανόργανα οξέα. Το Magma CR4 παρέχει ανώτερη προστασία κατά της επίθεσης οξέος σε υψηλές θερμοκρασίες. Ιδανικό για εξοπλισμό σε διυλιστήρια και χημικές εγκαταστάσεις που χειρίζονται θερμά ανόργανα οξέα. Διατηρεί τις προστατευτικές ιδιότητες ακόμη και σε ακραίες θερμοκρασίες και σε εξαιρετικά επιθετικά χημικά περιβάλλοντα.' WHERE code = '4341';

UPDATE products SET descriptionEn = 'A flexible chemical resistant epoxy coating for concrete protection with crack-bridging properties. This innovative coating bridges cracks while providing chemical resistance and protection against environmental degradation. Ideal for concrete structures subject to thermal movement and chemical exposure. Maintains flexibility and protective properties over extended service life.', descriptionEl = 'Ένα ευέλικτο χημικά ανθεκτικό εποξειδικό επίχρισμα για προστασία σκυροδέματος με ιδιότητες γεφύρωσης ρωγμών. Αυτό το καινοτόμο επίχρισμα γεφυρώνει τις ρωγμές παρέχοντας χημική αντίσταση και προστασία κατά της περιβαλλοντικής υποβάθμισης. Ιδανικό για δομές σκυροδέματος που υπόκεινται σε θερμική κίνηση και χημική έκθεση. Διατηρεί ευελιξία και προστατευτικές ιδιότητες κατά τη διάρκεια της επεκταμένης διάρκειας ζωής.' WHERE code = '4361';

UPDATE products SET descriptionEn = 'Hard wearing epoxy resin system for slip reduction on walking surfaces. Granogrip provides excellent slip resistance and durability. Ideal for creating safe walking surfaces on stairs, ramps, walkways, and other areas where slip resistance is critical. Can be applied to various substrates and maintains protective properties over extended service life.', descriptionEl = 'Ανθεκτικό σύστημα εποξειδικής ρητίνης για μείωση της ολίσθησης σε επιφάνειες περπατήματος. Το Granogrip παρέχει εξαιρετική αντιολίσθηση και ανθεκτικότητα. Ιδανικό για δημιουργία ασφαλών επιφανειών περπατήματος σε σκάλες, ράμπες, διαδρόμους και άλλες περιοχές όπου η αντιολίσθηση είναι κρίσιμη. Μπορεί να εφαρμοστεί σε διάφορα υποστρώματα και διατηρεί τις προστατευτικές ιδιότητες κατά τη διάρκεια της επεκταμένης διάρκειας ζωής.' WHERE code = '4411';

UPDATE products SET descriptionEn = 'An elastomeric expansion joint sealant for herozontal, vertical and sloped expansion joints. This flexible sealant accommodates movement while providing excellent protection against moisture ingress and environmental degradation. Ideal for protecting expansion joints in concrete structures, buildings, and industrial facilities. Maintains flexibility and sealing properties over extended service life.', descriptionEl = 'Ένα ελαστομερικό σφράγισμα διαστολής για οριζόντιες, κάθετες και κεκλιμένες αρμούς διαστολής. Αυτό το ευέλικτο σφράγισμα προσαρμόζεται στη κίνηση παρέχοντας εξαιρετική προστασία κατά της διείσδυσης υγρασίας και της περιβαλλοντικής υποβάθμισης. Ιδανικό για προστασία αρμών διαστολής σε δομές σκυροδέματος, κτίρια και βιομηχανικές εγκαταστάσεις. Διατηρεί ευελιξία και ιδιότητες σφράγισης κατά τη διάρκεια της επεκταμένης διάρκειας ζωής.' WHERE code = '4511';

UPDATE products SET descriptionEn = 'An elastomeric expansion joint sealant for sealing joints in surfaces including concrete, brick and stone. Magma-Flex Fluid provides flexible, durable sealing that accommodates movement and thermal expansion. Ideal for protecting expansion joints in buildings, concrete structures, and outdoor areas. Maintains sealing properties even under extreme weather conditions.', descriptionEl = 'Ένα ελαστομερικό σφράγισμα διαστολής για σφράγιση αρμών σε επιφάνειες συμπεριλαμβανομένου σκυροδέματος, τούβλου και πετρόχτιστων. Το Magma-Flex Fluid παρέχει ευέλικτη, ανθεκτική σφράγιση που προσαρμόζεται στη κίνηση και τη θερμική διαστολή. Ιδανικό για προστασία αρμών διαστολής σε κτίρια, δομές σκυροδέματος και εξωτερικές περιοχές. Διατηρεί τις ιδιότητες σφράγισης ακόμη και υπό ακραίες καιρικές συνθήκες.' WHERE code = '4521';

-- 5000 Series products
UPDATE products SET descriptionEn = 'A high performance static dissipative environmental polymer coating for protection of concrete and metal surfaces in demanding industrial environments. This advanced formulation provides long-term protection against chemical attack, UV exposure, and environmental degradation. Ideal for industrial facilities, chemical plants, and outdoor equipment requiring maximum durability.', descriptionEl = 'Ένα υψηλής απόδοσης στατικό διασκορπιστικό περιβαλλοντικό πολυμερικό επίχρισμα για προστασία των επιφανειών σκυροδέματος και μετάλλου σε απαιτητικά βιομηχανικά περιβάλλοντα. Αυτή η προηγμένη διατύπωση παρέχει μακροχρόνια προστασία κατά της χημικής επίθεσης, της έκθεσης στις υπεριώδεις ακτίνες και της περιβαλλοντικής υποβάθμισης. Ιδανικό για βιομηχανικές εγκαταστάσεις, χημικές εγκαταστάσεις και εξοπλισμό εξωτερικού χώρου που απαιτεί μέγιστη ανθεκτικότητα.' WHERE code = '5811';

UPDATE products SET descriptionEn = 'A high performance static dissipative environmental polymer coating specifically formulated for protection in wet conditions and high humidity environments. This advanced formulation maintains protective properties even when exposed to continuous moisture and water spray. Ideal for marine applications, water treatment facilities, and industrial equipment operating in wet environments.', descriptionEl = 'Ένα υψηλής απόδοσης στατικό διασκορπιστικό περιβαλλοντικό πολυμερικό επίχρισμα ειδικά διατυπωμένο για προστασία σε υγρές συνθήκες και περιβάλλοντα υψηλής υγρασίας. Αυτή η προηγμένη διατύπωση διατηρεί τις προστατευτικές ιδιότητες ακόμη και όταν εκτίθεται σε συνεχή υγρασία και ψεκασμό νερού. Ιδανικό για θαλάσσιες εφαρμογές, εγκαταστάσεις επεξεργασίας νερού και βιομηχανικό εξοπλισμό που λειτουργεί σε υγρά περιβάλλοντα.' WHERE code = '5813';
