-- Complete Belzona Product Catalog Import
-- All ~130 products with bilingual descriptions, categorized by series only

DELETE FROM products WHERE code LIKE '1%' OR code LIKE '2%' OR code LIKE '3%' OR code LIKE '4%' OR code LIKE '5%' OR code LIKE '6%' OR code LIKE '7%' OR code LIKE '8%' OR code LIKE '9%';

INSERT INTO products (code, nameEn, nameEl, category, descriptionEn, descriptionEl, published, createdAt, updatedAt) VALUES

-- 1000 Series - Metal Repair/Rebuilding Compounds
('1111', 'Belzona 1111 (Super Metal)', 'Belzona 1111 (Super Metal)', '1000 Series', 'An epoxy-based composite for metal repair. Two-part, epoxy-based composite designed for repair and protection of machinery and equipment. Provides excellent adhesion to metal surfaces and can be applied to wet and oil-contaminated substrates. High compressive strength, excellent wear resistance, and minimal surface preparation requirements.', 'Σύνθετο υλικό με βάση την εποξική ρητίνη για επισκευή μετάλλων. Δύο-συστατικό σύνθετο υλικό σχεδιασμένο για επισκευή και προστασία μηχανημάτων. Παρέχει εξαιρετική συνάφεια σε μεταλλικές επιφάνειες και μπορεί να εφαρμοστεί σε υγρές και λαδιού-μολυσμένες επιφάνειες.', true, NOW(), NOW()),
('1121', 'Belzona 1121 (Super XL-Metal)', 'Belzona 1121 (Super XL-Metal)', '1000 Series', 'Epoxy-based repair composite with extended working life for metal repair. Extended pot life makes it ideal for larger repair jobs. Maintains excellent properties with significantly longer application windows. Useful for complex repairs where careful application is critical.', 'Σύνθετο υλικό επισκευής με βάση την εποξική ρητίνη με παρατεταμένο χρόνο εργασίας. Επεκτεταμένος χρόνος εργασίας κατάλληλος για μεγαλύτερες εργασίες επισκευής.', true, NOW(), NOW()),
('1131', 'Belzona 1131 (Bearing Metal)', 'Belzona 1131 (Bearing Metal)', '1000 Series', 'Self-lubricating epoxy metal repair composite for creation of low friction surfaces. Contains solid lubricants providing continuous lubrication even without external lubricants. Specifically formulated for bearing repairs. Self-lubricating properties, excellent wear resistance, and bearing system compatibility.', 'Αυτο-λιπαινόμενο σύνθετο υλικό μετάλλου με βάση την εποξική ρητίνη. Περιέχει στερεά λιπαντικά που παρέχουν συνεχή λίπανση ακόμη και απουσία εξωτερικών λιπαντικών.', true, NOW(), NOW()),
('1151', 'Belzona 1151 (Smoothing Metal)', 'Belzona 1151 (Smoothing Metal)', '1000 Series', 'Metal repair composite for rebuilding pitting and metal loss caused by erosion and corrosion. Specifically designed to restore smooth surfaces on equipment damaged by erosive or corrosive attack. Excellent flow characteristics for precise surface restoration.', 'Σύνθετο υλικό επισκευής μετάλλου για ανοικοδόμηση κοιλοτήτων και απώλειας μετάλλου από διάβρωση και διάβρωση.', true, NOW(), NOW()),
('1161', 'Belzona 1161 (Super UW-Metal)', 'Belzona 1161 (Super UW-Metal)', '1000 Series', 'Epoxy-based repair composite for application to wet and oil contaminated metal surfaces. Formulated to cure properly on damp and contaminated substrates. Displaces moisture and oil, ensuring proper adhesion and cure. Ideal for emergency repairs in challenging conditions.', 'Σύνθετο υλικό επισκευής με βάση την εποξική ρητίνη για εφαρμογή σε υγρές και λαδιού-μολυσμένες μεταλλικές επιφάνειες.', true, NOW(), NOW()),
('1212', 'Belzona 1212', 'Belzona 1212', '1000 Series', 'Surface-tolerant epoxy composite for emergency in-situ metal repair of oil contaminated, wet and underwater substrates. Engineered for maximum surface tolerance. Cures properly on contaminated surfaces with excellent adhesion without extensive surface preparation.', 'Σύνθετο υλικό εποξικής ρητίνης ανεκτικό στην επιφάνεια για επείγουσα επισκευή μετάλλου σε δύσκολες συνθήκες.', true, NOW(), NOW()),
('1221', 'Belzona 1221 (Super E-Metal)', 'Belzona 1221 (Super E-Metal)', '1000 Series', 'Fast-curing metal repair composite for high speed emergency repairs. Offers rapid cure times allowing equipment to return to service quickly. Despite fast cure, maintains excellent mechanical properties and durability. Ideal for emergency situations minimizing downtime.', 'Γρήγορα σκληρυνόμενο σύνθετο υλικό επισκευής μετάλλου για επείγουσες επισκευές υψηλής ταχύτητας.', true, NOW(), NOW()),
('1251', 'Belzona 1251 (HA-Metal)', 'Belzona 1251 (HA-Metal)', '1000 Series', 'Heat activated metal repair composite for in-situ repair and protection of hot metal surfaces with minimal surface preparation. Can be applied directly to hot surfaces, curing through heat activation. Eliminates need for cooling and surface preparation.', 'Σύνθετο υλικό επισκευής μετάλλου που ενεργοποιείται από θερμότητα για επισκευή ζεστών μεταλλικών επιφανειών.', true, NOW(), NOW()),
('1311', 'Belzona 1311 (Ceramic R-Metal)', 'Belzona 1311 (Ceramic R-Metal)', '1000 Series', 'Ceramic filled epoxy-based composite for metal repair and erosion and corrosion protection. Contains ceramic particles providing enhanced erosion resistance and superior protection against corrosive environments. Ideal for equipment in harsh combined erosion and corrosion conditions.', 'Σύνθετο υλικό με βάση την εποξική ρητίνη γεμάτο κεραμικό για επισκευή μετάλλου και προστασία από διάβρωση και διάβρωση.', true, NOW(), NOW()),
('1321', 'Belzona 1321 (Ceramic S-Metal)', 'Belzona 1321 (Ceramic S-Metal)', '1000 Series', 'Ceramic filled epoxy coating for erosion and corrosion resistance of metal surfaces. Spray or brush-applied coating providing long-term protection against erosive and corrosive attack. Ceramic filler provides superior hardness and wear resistance.', 'Επίχρισμα εποξικής ρητίνης γεμάτο κεραμικό για αντίσταση στη διάβρωση και διάβρωση των μεταλλικών επιφανειών.', true, NOW(), NOW()),
('1331', 'Belzona 1331', 'Belzona 1331', '1000 Series', 'Spray or brush-applied epoxy coating for erosion and corrosion protection of equipment operating under continuous immersion. Provides excellent barrier protection suitable for long-term immersion service. Offers superior adhesion and flexibility.', 'Επίχρισμα εποξικής ρητίνης που εφαρμόζεται με ψεκασμό ή βούρτσα για προστασία από διάβρωση και διάβρωση.', true, NOW(), NOW()),
('1341', 'Belzona 1341 (Supermetalglide)', 'Belzona 1341 (Supermetalglide)', '1000 Series', 'Epoxy coating designed to improve efficiency of pumps, pipes, valves and fluid handling equipment while providing outstanding erosion and corrosion protection. Reduces friction losses and improves flow characteristics, resulting in energy savings and improved performance.', 'Επίχρισμα εποξικής ρητίνης σχεδιασμένο για να βελτιώσει την απόδοση αντλιών, σωλήνων, βαλβίδων και άλλου εξοπλισμού χειρισμού ρευστών.', true, NOW(), NOW()),
('1341N', 'Belzona 1341N (Supermetalglide NSF)', 'Belzona 1341N (Supermetalglide NSF)', '1000 Series', 'NSF/ANSI 61 approved epoxy coating for improving efficiency of fluid handling equipment with outstanding erosion and corrosion protection. Specifically formulated for potable water applications. Meets all regulatory requirements for drinking water contact.', 'Επίχρισμα εποξικής ρητίνης εγκεκριμένο NSF/ANSI 61 σχεδιασμένο για εφαρμογές πόσιμου νερού.', true, NOW(), NOW()),
('1381', 'Belzona 1381', 'Belzona 1381', '1000 Series', 'Spray or brush-applied high temperature epoxy coating for erosion and corrosion protection of equipment operating under continuous immersion. Maintains protective properties at elevated temperatures. Provides excellent barrier protection.', 'Επίχρισμα εποξικής ρητίνης υψηλής θερμοκρασίας που εφαρμόζεται με ψεκασμό ή βούρτσα για προστασία από διάβρωση και διάβρωση.', true, NOW(), NOW()),
('1391S', 'Belzona 1391S', 'Belzona 1391S', '1000 Series', 'Spray-applied epoxy coating for corrosion protection of high temperature equipment operating under immersion. Specifically formulated for spray application. Provides excellent protection at elevated temperatures.', 'Επίχρισμα εποξικής ρητίνης που εφαρμόζεται με ψεκασμό για προστασία από διάβρωση του εξοπλισμού υψηλής θερμοκρασίας.', true, NOW(), NOW()),
('1391T', 'Belzona 1391T', 'Belzona 1391T', '1000 Series', 'Hand-applied erosion and corrosion resistant coating for high temperature equipment operating under immersion. Designed for manual application. Provides superior protection in high temperature immersion environments.', 'Επίχρισμα αντίστασης σε διάβρωση και διάβρωση που εφαρμόζεται χειροκίνητα για εξοπλισμό υψηλής θερμοκρασίας.', true, NOW(), NOW()),
('1392', 'Belzona 1392 (Ceramic HT2)', 'Belzona 1392 (Ceramic HT2)', '1000 Series', 'Erosion, corrosion and chemical resistant coating for high temperature equipment operating under immersion. Combines ceramic technology with high temperature epoxy chemistry. Provides superior protection in demanding environments.', 'Επίχρισμα αντίστασης σε διάβρωση, διάβρωση και χημική προσβολή για εξοπλισμό υψηλής θερμοκρασίας.', true, NOW(), NOW()),
('1511', 'Belzona 1511 (Super HT-Metal)', 'Belzona 1511 (Super HT-Metal)', '1000 Series', 'High temperature epoxy repair composite for rebuilding equipment damaged by erosion and corrosion. Maintains properties at elevated temperatures. Provides excellent repair capabilities for high temperature applications.', 'Σύνθετο υλικό επισκευής εποξικής ρητίνης υψηλής θερμοκρασίας για ανοικοδόμηση εξοπλισμού που έχει υποστεί ζημιά.', true, NOW(), NOW()),
('1523', 'Belzona 1523', 'Belzona 1523', '1000 Series', 'High temperature spray-applied epoxy coating for internal lining of equipment operating under continuous immersion. Provides outstanding corrosion resistance. Designed for spray application with excellent internal protection.', 'Επίχρισμα εποξικής ρητίνης υψηλής θερμοκρασίας που εφαρμόζεται με ψεκασμό για εσωτερική επένδυση εξοπλισμού.', true, NOW(), NOW()),
('1593', 'Belzona 1593', 'Belzona 1593', '1000 Series', 'High temperature hand-applied epoxy coating for internal lining of equipment operating under continuous immersion. Provides outstanding corrosion resistance. Designed for manual application with excellent internal protection.', 'Επίχρισμα εποξικής ρητίνης υψηλής θερμοκρασίας που εφαρμόζεται χειροκίνητα για εσωτερική επένδυση εξοπλισμού.', true, NOW(), NOW()),
('1811', 'Belzona 1811 (Ceramic Carbide)', 'Belzona 1811 (Ceramic Carbide)', '1000 Series', 'Abrasion resistant composite material for repair and lining of metal surfaces subject to erosive attack. Contains ceramic carbide particles providing exceptional hardness and wear resistance. Ideal for equipment experiencing severe abrasive wear.', 'Σύνθετο υλικό αντίστασης στη φθορά για επισκευή και επένδυση μεταλλικών επιφανειών που υπόκεινται σε διαβρωτική προσβολή.', true, NOW(), NOW()),
('1812', 'Belzona 1812 (Ceramic Carbide FP)', 'Belzona 1812 (Ceramic Carbide FP)', '1000 Series', 'Abrasion resistant composite material for repair and lining of metal surfaces suffering from fine particle erosion. Specifically formulated to resist fine particle erosion. Provides superior protection in this application.', 'Σύνθετο υλικό αντίστασης στη φθορά για επισκευή και επένδυση μεταλλικών επιφανειών που υπόκεινται σε διάβρωση λεπτών σωματιδίων.', true, NOW(), NOW()),
('1813', 'Belzona 1813', 'Belzona 1813', '1000 Series', 'Highly abrasion resistant composite material for repair and lining of metal surfaces operating at high temperatures. Combines abrasion resistance with high temperature capability for demanding applications.', 'Σύνθετο υλικό υψηλής αντίστασης στη φθορά για επισκευή και επένδυση μεταλλικών επιφανειών που λειτουργούν σε υψηλές θερμοκρασίες.', true, NOW(), NOW()),
('1814', 'Belzona 1814', 'Belzona 1814', '1000 Series', 'Abrasion resistant composite material for repair and protection of metal surfaces. Provides general-purpose abrasion resistance suitable for wide range of applications.', 'Σύνθετο υλικό αντίστασης στη φθορά για επισκευή και προστασία μεταλλικών επιφανειών.', true, NOW(), NOW()),
('1818', 'Belzona 1818', 'Belzona 1818', '1000 Series', 'Fast curing, surface tolerant, abrasion resistant general-purpose protection system. Combines rapid cure with surface tolerance and abrasion resistance. Ideal for emergency repairs requiring quick turnaround.', 'Σύστημα γρήγορης σκλήρυνσης, ανεκτικό στην επιφάνεια, αντίστασης στη φθορά γενικής χρήσης.', true, NOW(), NOW()),
('1821', 'Belzona 1821 (Fluid Metal)', 'Belzona 1821 (Fluid Metal)', '1000 Series', 'Epoxy coating system used with Belzona aggregates to reduce slippage on metallic surfaces. Provides grip and traction on smooth metal surfaces, improving safety and equipment efficiency.', 'Σύστημα επίχρισης εποξικής ρητίνης που χρησιμοποιείται σε συνδυασμό με συσσωματώματα Belzona για μείωση της ολίσθησης.', true, NOW(), NOW()),

-- 2000 Series - Elastomeric Polymers
('2111', 'Belzona 2111 (D&A Hi-Build Elastomer)', 'Belzona 2111 (D&A Hi-Build Elastomer)', '2000 Series', 'Flexible abrasion resistant polyurethane elastomer for repair, rebuilding and coating of rubber components and metal surfaces. Provides excellent flexibility combined with abrasion resistance. Ideal for rubber component repairs.', 'Εύκαμπτο πολυουρεθανικό ελαστομερές αντίστασης στη φθορά για επισκευή, ανοικοδόμηση και επίχρισμα συστατικών από καουτσούκ.', true, NOW(), NOW()),
('2131', 'Belzona 2131 (D&A Fluid Elastomer)', 'Belzona 2131 (D&A Fluid Elastomer)', '2000 Series', 'Flexible abrasion resistant polyurethane elastomer for casting of rubber components and coating of metal and rubber surfaces. Offers excellent flow characteristics and can be cast into molds for custom component creation.', 'Εύκαμπτο πολυουρεθανικό ελαστομερές αντίστασης στη φθορά για χύτευση συστατικών από καουτσούκ και επίχρισμα επιφανειών.', true, NOW(), NOW()),
('2141', 'Belzona 2141 (ACR-Fluid Elastomer)', 'Belzona 2141 (ACR-Fluid Elastomer)', '2000 Series', 'Flexible cavitation and abrasion resistant polyurethane elastomer for coating of metal and rubber components. Specifically formulated to resist cavitation damage while maintaining excellent flexibility and abrasion resistance.', 'Εύκαμπτο πολυουρεθανικό ελαστομερές αντίστασης σε κοιλοτομία και φθορά για επίχρισμα μεταλλικών και ελαστικών συστατικών.', true, NOW(), NOW()),
('2211', 'Belzona 2211 (MP Hi-Build Elastomer)', 'Belzona 2211 (MP Hi-Build Elastomer)', '2000 Series', 'Flexible multi-purpose polyurethane elastomer for repair, rebuilding and coating of rubber components and metal surfaces. Provides versatile performance across wide range of applications with excellent flexibility and durability.', 'Εύκαμπτο πολυουρεθανικό ελαστομερές πολλαπλής χρήσης για επισκευή, ανοικοδόμηση και επίχρισμα συστατικών από καουτσούκ.', true, NOW(), NOW()),
('2221', 'Belzona 2221 (MP Fluid Elastomer)', 'Belzona 2221 (MP Fluid Elastomer)', '2000 Series', 'Tough, flexible multi-purpose polyurethane elastomer for repair and coating of rubber components and metal surfaces and casting of new components. Combines toughness with flexibility and can be used for casting applications.', 'Ανθεκτικό, εύκαμπτο πολυουρεθανικό ελαστομερές πολλαπλής χρήσης για επισκευή και επίχρισμα συστατικών από καουτσούκ.', true, NOW(), NOW()),
('2311', 'Belzona 2311 (SR Elastomer)', 'Belzona 2311 (SR Elastomer)', '2000 Series', 'Fast-curing, abrasion resistant polyurethane elastomer for high speed emergency repairs, rebuilding and coating of rubber components and metal surfaces. Offers rapid cure times while maintaining excellent mechanical properties.', 'Γρήγορα σκληρυνόμενο, πολυουρεθανικό ελαστομερές αντίστασης στη φθορά για επείγουσες επισκευές υψηλής ταχύτητας.', true, NOW(), NOW()),

-- 3000 Series - Waterproofing Systems
('3111', 'Belzona 3111 (Flexible Membrane)', 'Belzona 3111 (Flexible Membrane)', '3000 Series', 'Single component, liquid-applied roof coating for long-term roof protection and waterproofing. Provides flexible, seamless protection and can accommodate building movement and thermal expansion.', 'Επίχρισμα στέγης ενός συστατικού, υγρής εφαρμογής για μακροπρόθεσμη προστασία και αδιαβροχοποίηση της στέγης.', true, NOW(), NOW()),
('3121', 'Belzona 3121 (MR7)', 'Belzona 3121 (MR7)', '3000 Series', 'Liquid-applied emergency roof repair material providing instant waterproofing of leaking roof areas. Cures quickly and provides immediate weather protection for emergency roof repairs.', 'Υλικό επείγουσας επισκευής στέγης υγρής εφαρμογής που παρέχει άμεση αδιαβροχοποίηση των διαρρεόντων περιοχών.', true, NOW(), NOW()),
('3131', 'Belzona 3131 (WG Membrane)', 'Belzona 3131 (WG Membrane)', '3000 Series', 'Liquid-applied roof coating for long-term protection and waterproofing of roofs which can be applied during winter weather conditions. Maintains performance in cold temperatures with reliable year-round protection.', 'Επίχρισμα στέγης υγρής εφαρμογής για μακροπρόθεσμη προστασία που μπορεί να εφαρμοστεί κατά τη διάρκεια χειμερινών συνθηκών.', true, NOW(), NOW()),
('3211', 'Belzona 3211 (Lagseal)', 'Belzona 3211 (Lagseal)', '3000 Series', 'Single component, seamless and flexible coating for encapsulation of all types of thermal insulation and cladding systems. Provides weatherproof protection for insulation systems and maintains thermal efficiency.', 'Επίχρισμα ενός συστατικού, άρρευστο και εύκαμπτο για ενκαψύλωση όλων των τύπων συστημάτων θερμικής μόνωσης.', true, NOW(), NOW()),
('3412', 'Belzona 3412', 'Belzona 3412', '3000 Series', 'Flexible and peelable system for encapsulating flanges and bolt fastenings to protect against moisture ingress and prevent corrosion. Can be easily removed for maintenance and reapplied as needed.', 'Σύστημα εύκαμπτο και αποκολλώμενο για ενκαψύλωση φλάντζων και κοχλιών για προστασία από την εισχώρηση υγρασίας.', true, NOW(), NOW()),

-- 4000 Series - Concrete Protection
('4111', 'Belzona 4111 (Magma-Quartz)', 'Belzona 4111 (Magma-Quartz)', '4000 Series', 'Epoxy repair composite for concrete and stone repair, resurfacing and protection. Provides excellent adhesion to concrete substrates and offers superior durability for concrete repairs.', 'Σύνθετο υλικό επισκευής εποξικής ρητίνης για επισκευή, ανακαίνιση και προστασία σκυροδέματος και πέτρας.', true, NOW(), NOW()),
('4124', 'Belzona 4124 (Bulkfill)', 'Belzona 4124 (Bulkfill)', '4000 Series', 'Epoxy-based resin designed to be used with aggregate for reparation, resurfacing and rebuilding of concrete and stonework damaged by impact, vibration, chemical and environmental attack. Offers cost-effective bulk repair solutions.', 'Μια εποξική ρητίνη σχεδιασμένη για χρήση με συσσωμάτωμα για επισκευή και ανοικοδόμηση σκυροδέματος και λιθοδομής.', true, NOW(), NOW()),
('4131', 'Belzona 4131 (Magma-Screed)', 'Belzona 4131 (Magma-Screed)', '4000 Series', 'Epoxy repair composite for resurfacing and protection of concrete and stone areas. Provides smooth, durable surfaces suitable for high-traffic areas.', 'Σύνθετο υλικό επισκευής εποξικής ρητίνης για ανακαίνιση και προστασία περιοχών σκυροδέματος και πέτρας.', true, NOW(), NOW()),
('4141', 'Belzona 4141 (Magma-Build)', 'Belzona 4141 (Magma-Build)', '4000 Series', 'Lightweight epoxy repair composite for vertical and overhead concrete and stone repairs. Reduces fatigue during application and provides excellent adhesion on vertical surfaces.', 'Ελαφρύ σύνθετο υλικό επισκευής εποξικής ρητίνης για κάθετες και οριζόντιες επισκευές σκυροδέματος.', true, NOW(), NOW()),
('4151', 'Belzona 4151 (Magma-Quartz Resin)', 'Belzona 4151 (Magma-Quartz Resin)', '4000 Series', 'Epoxy resin for treatment and protection of concrete surfaces exposed to chemical attack and abrasion. Designed for use with aggregates to create protective systems.', 'Μια εποξική ρητίνη για την επεξεργασία και προστασία των επιφανειών σκυροδέματος που εκτίθενται σε χημική προσβολή.', true, NOW(), NOW()),
('4154', 'Belzona 4154 (Bulkfill Resin)', 'Belzona 4154 (Bulkfill Resin)', '4000 Series', 'Epoxy-based resin designed to be used with aggregate for reparation, resurfacing and rebuilding of concrete and stonework. Resin component for bulk applications.', 'Μια εποξική ρητίνη σχεδιασμένη για χρήση με συσσωμάτωμα για επισκευή και ανοικοδόμηση σκυροδέματος.', true, NOW(), NOW()),
('4181', 'Belzona 4181 (AHR Magma-Quartz)', 'Belzona 4181 (AHR Magma-Quartz)', '4000 Series', 'Acid and heat resistant epoxy repair composite for concrete and stone repair, resurfacing and protection. Provides superior protection in chemically aggressive environments.', 'Σύνθετο υλικό επισκευής εποξικής ρητίνης ανθεκτικό σε οξέα και θερμότητα για επισκευή σκυροδέματος.', true, NOW(), NOW()),
('4301', 'Belzona 4301 (Magma CR1 Hi-Build)', 'Belzona 4301 (Magma CR1 Hi-Build)', '4000 Series', 'Chemical resistant epoxy material for rebuilding metal and concrete surfaces and protection against chemical attack. Provides excellent chemical resistance and durability.', 'Χημικά ανθεκτικό υλικό εποξικής ρητίνης για ανοικοδόμηση μεταλλικών και σκυροδέματος επιφανειών.', true, NOW(), NOW()),
('4311', 'Belzona 4311 (Magma CR1)', 'Belzona 4311 (Magma CR1)', '4000 Series', 'Chemical resistant epoxy coating for protection of concrete and metal surfaces. Provides long-term protection against chemical attack and environmental degradation.', 'Χημικά ανθεκτικό επίχρισμα εποξικής ρητίνης για προστασία των επιφανειών σκυροδέματος και μετάλλου.', true, NOW(), NOW()),
('4331', 'Belzona 4331 (Magma CR3)', 'Belzona 4331 (Magma CR3)', '4000 Series', 'High temperature epoxy coating for protection of concrete and metal surfaces in contact with hot organic acids and other chemicals. Maintains protective properties at elevated temperatures.', 'Επίχρισμα εποξικής ρητίνης υψηλής θερμοκρασίας για προστασία των επιφανειών σκυροδέματος και μετάλλου.', true, NOW(), NOW()),
('4341', 'Belzona 4341 (Magma CR4)', 'Belzona 4341 (Magma CR4)', '4000 Series', 'High temperature epoxy coating for concrete and metal surfaces in contact with hot inorganic acids. Provides superior protection in highly corrosive chemical environments.', 'Επίχρισμα εποξικής ρητίνης υψηλής θερμοκρασίας για επιφάνειες σε επαφή με ζεστά ανόργανα οξέα.', true, NOW(), NOW()),
('4351', 'Belzona 4351 (Magma CR5)', 'Belzona 4351 (Magma CR5)', '4000 Series', 'Static dissipative, chemical resistant coating for protection of concrete and metal surfaces. Provides electrostatic discharge protection while maintaining chemical resistance.', 'Επίχρισμα διαχυτικό στατικής ηλεκτρικότητας, χημικά ανθεκτικό για προστασία των επιφανειών σκυροδέματος.', true, NOW(), NOW()),
('4361', 'Belzona 4361', 'Belzona 4361', '4000 Series', 'Flexible chemical resistant epoxy coating for concrete protection with crack-bridging properties. Can accommodate substrate movement and prevent crack propagation.', 'Εύκαμπτο χημικά ανθεκτικό επίχρισμα εποξικής ρητίνης για προστασία σκυροδέματος με ιδιότητες γεφύρωσης ρωγμών.', true, NOW(), NOW()),
('4411', 'Belzona 4411 (Granogrip)', 'Belzona 4411 (Granogrip)', '4000 Series', 'Hard wearing epoxy resin system for slip reduction on walking surfaces. Provides excellent traction and safety on concrete floors and walkways.', 'Σύστημα εποξικής ρητίνης ανθεκτικό στη φθορά για μείωση της ολίσθησης σε επιφάνειες περπατήματος.', true, NOW(), NOW()),
('4511', 'Belzona 4511', 'Belzona 4511', '4000 Series', 'Elastomeric expansion joint sealant for horizontal, vertical and sloped expansion joints. Provides flexible, durable sealing for building movement.', 'Ελαστομερές σφραγιστικό αρμού διαστολής για οριζόντιους, κάθετους και κεκλιμένους αρμούς διαστολής.', true, NOW(), NOW()),
('4521', 'Belzona 4521 (Magma-Flex Fluid)', 'Belzona 4521 (Magma-Flex Fluid)', '4000 Series', 'Elastomeric expansion joint sealant for sealing joints in surfaces including concrete, brick and stone. Provides flexible, long-lasting sealing for various substrate types.', 'Ελαστομερές σφραγιστικό αρμού διαστολής για σφράγιση αρμών σε επιφάνειες σκυροδέματος, τούβλου και πέτρας.', true, NOW(), NOW()),

-- 5000 Series - Environmental Polymers (Protective Coatings)
('5111', 'Belzona 5111 (Ceramic Cladding)', 'Belzona 5111 (Ceramic Cladding)', '5000 Series', 'Urethane coating for protection of metallic and masonry surfaces against chemical, abrasive and corrosive attack. Provides durable, long-term protection in harsh environments.', 'Επίχρισμα πολυουρεθάνης για προστασία μεταλλικών και τοιχοδομικών επιφανειών κατά της χημικής, φθοράς και διαβρωτικής προσβολής.', true, NOW(), NOW()),
('5122', 'Belzona 5122 (Clear Cladding)', 'Belzona 5122 (Clear Cladding)', '5000 Series', 'Clear, water-repellent treatment for masonry surfaces. Provides transparent protection while maintaining aesthetic appearance of masonry.', 'Διαφανής, υδρόφοβη επεξεργασία για επιφάνειες τοιχοδομής που διατηρεί την αισθητική εμφάνιση.', true, NOW(), NOW()),
('5231', 'Belzona 5231 (SG Laminate)', 'Belzona 5231 (SG Laminate)', '5000 Series', 'Epoxy floor coating which provides excellent chemical, abrasion and slip resistance. Ideal for industrial and commercial floor applications.', 'Επίχρισμα δαπέδου εποξικής ρητίνης που παρέχει εξαιρετική χημική, αντίσταση στη φθορά και ολίσθηση.', true, NOW(), NOW()),
('5233', 'Belzona 5233', 'Belzona 5233', '5000 Series', 'Waterborne, 100% solids, UV stable floor coating to provide floor protection and slip-resistance at commercial and industrial facilities. Environmentally friendly formulation.', 'Επίχρισμα δαπέδου υδατικής βάσης, 100% στερεά, σταθερό στο UV για προστασία δαπέδου και αντίσταση στη ολίσθηση.', true, NOW(), NOW()),
('5711', 'Belzona 5711', 'Belzona 5711', '5000 Series', 'High Performance, Fast Curing System for Leading Edge Repairs. Provides rapid curing with excellent mechanical properties for leading edge applications.', 'Σύστημα υψηλής απόδοσης, γρήγορης σκλήρυνσης για επισκευές μπροστινής άκρης.', true, NOW(), NOW()),
('5721', 'Belzona 5721', 'Belzona 5721', '5000 Series', 'UV and Erosion Resistant Coating for Leading Edge Protection. Provides protection against UV degradation and erosive attack on leading edges.', 'Επίχρισμα ανθεκτικό στο UV και διάβρωση για προστασία της μπροστινής άκρης.', true, NOW(), NOW()),
('5811', 'Belzona 5811 (Immersion Grade)', 'Belzona 5811 (Immersion Grade)', '5000 Series', 'Epoxy coating designed for corrosion and chemical protection of equipment operating under immersion. Provides excellent barrier protection and chemical resistance for submerged applications.', 'Επίχρισμα εποξικής ρητίνης σχεδιασμένο για προστασία από διάβρωση και χημική προστασία του εξοπλισμού που λειτουργεί υπό βύθιση.', true, NOW(), NOW()),
('5811DW2', 'Belzona 5811DW2 (Immersion Grade)', 'Belzona 5811DW2 (Immersion Grade)', '5000 Series', 'Epoxy coating designed for corrosion and chemical protection of equipment operating under immersion. Enhanced formulation for demanding underwater applications.', 'Επίχρισμα εποξικής ρητίνης σχεδιασμένο για προστασία από διάβρωση του εξοπλισμού που λειτουργεί υπό βύθιση.', true, NOW(), NOW()),
('5812DW', 'Belzona 5812 DW', 'Belzona 5812 DW', '5000 Series', 'Epoxy-based coating for corrosion protection, approved for contact with drinking water. Meets NSF/ANSI 61 standards for potable water applications.', 'Επίχρισμα εποξικής ρητίνης για προστασία από διάβρωση, εγκεκριμένο για επαφή με πόσιμο νερό.', true, NOW(), NOW()),
('5813', 'Belzona 5813', 'Belzona 5813', '5000 Series', 'High Performance Static Dissipative, 100% solids, Barrier Coating. Provides electrostatic discharge protection with excellent barrier properties.', 'Επίχρισμα φραγμού υψηλής απόδοσης διαχυτικό στατικής ηλεκτρικότητας, 100% στερεά.', true, NOW(), NOW()),
('5815', 'Belzona 5815', 'Belzona 5815', '5000 Series', 'Containment Grade, Flexible, Barrier Coating. Provides flexible barrier protection suitable for containment applications.', 'Επίχρισμα φραγμού βαθμού περιορισμού, εύκαμπτο, φραγμό.', true, NOW(), NOW()),
('5821', 'Belzona 5821', 'Belzona 5821', '5000 Series', 'High performance epoxy-based coating for protection of critical equipment operating under immersion and erosive conditions. Combines immersion resistance with erosion protection.', 'Επίχρισμα εποξικής ρητίνης υψηλής απόδοσης για προστασία κρίσιμου εξοπλισμού που λειτουργεί υπό βύθιση και διαβρωτικές συνθήκες.', true, NOW(), NOW()),
('5831', 'Belzona 5831 (ST-Barrier)', 'Belzona 5831 (ST-Barrier)', '5000 Series', 'Moisture-tolerant epoxy coating for corrosion protection of wet and oil contaminated surfaces. Allows application in challenging surface conditions.', 'Επίχρισμα εποξικής ρητίνης ανεκτικό στην υγρασία για προστασία από διάβρωση των υγρών και λαδιού-μολυσμένων επιφανειών.', true, NOW(), NOW()),
('5831LT', 'Belzona 5831LT', 'Belzona 5831LT', '5000 Series', 'Moisture-tolerant epoxy coating for corrosion protection of wet and oil contaminated surfaces at lower temperatures. Extends application range to cold conditions.', 'Επίχρισμα εποξικής ρητίνης ανεκτικό στην υγρασία για προστασία από διάβρωση σε χαμηλότερες θερμοκρασίες.', true, NOW(), NOW()),
('5841', 'Belzona 5841', 'Belzona 5841', '5000 Series', 'Epoxy coating requiring minimal surface preparation for in-situ repair and protection of hot metal surfaces subject to corrosion under insulation. Ideal for CUI applications.', 'Επίχρισμα εποξικής ρητίνης που απαιτεί ελάχιστη προετοιμασία επιφάνειας για επισκευή και προστασία ζεστών μεταλλικών επιφανειών.', true, NOW(), NOW()),
('5851', 'Belzona 5851 (HA-Barrier)', 'Belzona 5851 (HA-Barrier)', '5000 Series', 'Heat activated epoxy coating for in-situ application to hot metal surfaces with minimal preparation to protect against corrosion. Cures through heat activation.', 'Επίχρισμα εποξικής ρητίνης που ενεργοποιείται από θερμότητα για εφαρμογή σε ζεστές μεταλλικές επιφάνειες με ελάχιστη προετοιμασία.', true, NOW(), NOW()),
('5871', 'Belzona 5871', 'Belzona 5871', '5000 Series', '"Cool-to-touch" thermal insulation barrier against corrosion. Provides both thermal insulation and corrosion protection properties.', '"Cool-to-touch" φραγμό θερμικής μόνωσης κατά της διάβρωσης που παρέχει θερμική μόνωση και προστασία από διάβρωση.', true, NOW(), NOW()),
('5892', 'Belzona 5892', 'Belzona 5892', '5000 Series', 'Epoxy coating for corrosion and chemical protection of high temperature equipment operating under immersion. Maintains protection at elevated temperatures.', 'Επίχρισμα εποξικής ρητίνης για προστασία από διάβρωση και χημική προστασία του εξοπλισμού υψηλής θερμοκρασίας.', true, NOW(), NOW()),

-- Other Products
('6111', 'Belzona 6111 (Liquid Anode)', 'Belzona 6111 (Liquid Anode)', 'Other Products', 'Environmental corrosion protection epoxy coating for metallic surfaces. Provides cathodic protection properties.', 'Περιβαλλοντικό επίχρισμα εποξικής ρητίνης προστασίας από διάβρωση για μεταλλικές επιφάνειες.', true, NOW(), NOW()),
('7111', 'Belzona 7111', 'Belzona 7111', 'Other Products', 'Specially designed to endure the physical and thermal shock common to marine environments. Provides superior protection in harsh marine conditions.', 'Ειδικά σχεδιασμένο για να αντέχει το φυσικό και θερμικό σοκ που είναι κοινό στο θαλάσσιο περιβάλλον.', true, NOW(), NOW()),
('7211', 'Belzona 7211', 'Belzona 7211', 'Other Products', 'Epoxy based system specifically designed as a deep pour grout for up to 20.5 cm (8 in). Ideal for deep grouting applications.', 'Σύστημα με βάση την εποξική ρητίνη ειδικά σχεδιασμένο ως βαθύ χυτό κονίαμα για έως 20,5 εκ.', true, NOW(), NOW()),
('7311', 'Belzona 7311', 'Belzona 7311', 'Other Products', 'High mechanical strength, fatigue resistant structural adhesive. Provides excellent bonding for structural applications.', 'Δομική κόλλα υψηλής μηχανικής αντοχής, ανθεκτική στην κόπωση.', true, NOW(), NOW()),
('8211', 'Belzona 8211 (HP Anti-Seize)', 'Belzona 8211 (HP Anti-Seize)', 'Other Products', 'Metal-free anti-seize compound which protects mating metal parts from seizure and galling caused by high temperature, corrosion and chemical attack.', 'Σύνθεση χωρίς μέταλλο που προστατεύει τα σύνδετα μεταλλικά μέρη από κατάσχεση και φθορά που προκαλείται από υψηλή θερμοκρασία.', true, NOW(), NOW()),
('8311', 'Belzona 8311 (Nato Fluid)', 'Belzona 8311 (Nato Fluid)', 'Other Products', 'Lubrication system for penetration, lubrication, de-watering and corrosion protection of components. Multi-purpose protective fluid.', 'Σύστημα λίπανσης για διείσδυση, λίπανση, αποξήρανση και προστασία από διάβρωση των συστατικών.', true, NOW(), NOW()),
('9611', 'Belzona 9611', 'Belzona 9611', 'Other Products', 'Mouldable, rapid-curing putty stick for emergency live leak sealing on low pressure leaks prior to application of permanent Belzona solution.', 'Πλαστικό, γρήγορα σκληρυνόμενο ραβδί για επείγουσα σφράγιση διαρροών σε χαμηλή πίεση.', true, NOW(), NOW()),
('9631', 'Belzona 9631', 'Belzona 9631', 'Other Products', 'Leak-sealing kit containing a 5cm x 150cm / 2in x 60in fiberglass pre-impregnated wrap which is activated by water.', 'Κιτ σφράγισης διαρροών που περιέχει ένα περιτύλιγμα υαλονιτών προ-εμποτισμένο που ενεργοποιείται από νερό.', true, NOW(), NOW());
